package com.ctgu.j604.springbootchat.model;

public class GroupLinkUserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_link_user.group_id
     *
     * @mbg.generated Sat Aug 21 23:55:39 CST 2021
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_link_user.user_id
     *
     * @mbg.generated Sat Aug 21 23:55:39 CST 2021
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_link_user.group_id
     *
     * @return the value of group_link_user.group_id
     *
     * @mbg.generated Sat Aug 21 23:55:39 CST 2021
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_link_user.group_id
     *
     * @param groupId the value for group_link_user.group_id
     *
     * @mbg.generated Sat Aug 21 23:55:39 CST 2021
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_link_user.user_id
     *
     * @return the value of group_link_user.user_id
     *
     * @mbg.generated Sat Aug 21 23:55:39 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_link_user.user_id
     *
     * @param userId the value for group_link_user.user_id
     *
     * @mbg.generated Sat Aug 21 23:55:39 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}