package com.ctgu.j604.springbootchat.model;

import java.util.Date;

public class GroupLinkUser extends GroupLinkUserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_link_user.member_comment
     *
     * @mbg.generated Sat Aug 21 23:55:39 CST 2021
     */
    private String memberComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_link_user.add_time
     *
     * @mbg.generated Sat Aug 21 23:55:39 CST 2021
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_link_user.member_comment
     *
     * @return the value of group_link_user.member_comment
     *
     * @mbg.generated Sat Aug 21 23:55:39 CST 2021
     */
    public String getMemberComment() {
        return memberComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_link_user.member_comment
     *
     * @param memberComment the value for group_link_user.member_comment
     *
     * @mbg.generated Sat Aug 21 23:55:39 CST 2021
     */
    public void setMemberComment(String memberComment) {
        this.memberComment = memberComment == null ? null : memberComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_link_user.add_time
     *
     * @return the value of group_link_user.add_time
     *
     * @mbg.generated Sat Aug 21 23:55:39 CST 2021
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_link_user.add_time
     *
     * @param addTime the value for group_link_user.add_time
     *
     * @mbg.generated Sat Aug 21 23:55:39 CST 2021
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}