package com.ctgu.j604.springbootchat.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GroupExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_group
     *
     * @mbg.generated Sat Aug 21 23:34:51 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_group
     *
     * @mbg.generated Sat Aug 21 23:34:51 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_group
     *
     * @mbg.generated Sat Aug 21 23:34:51 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbg.generated Sat Aug 21 23:34:51 CST 2021
     */
    public GroupExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbg.generated Sat Aug 21 23:34:51 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbg.generated Sat Aug 21 23:34:51 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbg.generated Sat Aug 21 23:34:51 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbg.generated Sat Aug 21 23:34:51 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbg.generated Sat Aug 21 23:34:51 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbg.generated Sat Aug 21 23:34:51 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbg.generated Sat Aug 21 23:34:51 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbg.generated Sat Aug 21 23:34:51 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbg.generated Sat Aug 21 23:34:51 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbg.generated Sat Aug 21 23:34:51 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_group
     *
     * @mbg.generated Sat Aug 21 23:34:51 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGroupIdIsNull() {
            addCriterion("group_id is null");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNotNull() {
            addCriterion("group_id is not null");
            return (Criteria) this;
        }

        public Criteria andGroupIdEqualTo(Integer value) {
            addCriterion("group_id =", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotEqualTo(Integer value) {
            addCriterion("group_id <>", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThan(Integer value) {
            addCriterion("group_id >", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("group_id >=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThan(Integer value) {
            addCriterion("group_id <", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThanOrEqualTo(Integer value) {
            addCriterion("group_id <=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIn(List<Integer> values) {
            addCriterion("group_id in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotIn(List<Integer> values) {
            addCriterion("group_id not in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdBetween(Integer value1, Integer value2) {
            addCriterion("group_id between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotBetween(Integer value1, Integer value2) {
            addCriterion("group_id not between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupNumIsNull() {
            addCriterion("group_num is null");
            return (Criteria) this;
        }

        public Criteria andGroupNumIsNotNull() {
            addCriterion("group_num is not null");
            return (Criteria) this;
        }

        public Criteria andGroupNumEqualTo(String value) {
            addCriterion("group_num =", value, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupNumNotEqualTo(String value) {
            addCriterion("group_num <>", value, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupNumGreaterThan(String value) {
            addCriterion("group_num >", value, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupNumGreaterThanOrEqualTo(String value) {
            addCriterion("group_num >=", value, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupNumLessThan(String value) {
            addCriterion("group_num <", value, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupNumLessThanOrEqualTo(String value) {
            addCriterion("group_num <=", value, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupNumLike(String value) {
            addCriterion("group_num like", value, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupNumNotLike(String value) {
            addCriterion("group_num not like", value, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupNumIn(List<String> values) {
            addCriterion("group_num in", values, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupNumNotIn(List<String> values) {
            addCriterion("group_num not in", values, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupNumBetween(String value1, String value2) {
            addCriterion("group_num between", value1, value2, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupNumNotBetween(String value1, String value2) {
            addCriterion("group_num not between", value1, value2, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupMemberCountIsNull() {
            addCriterion("group_member_count is null");
            return (Criteria) this;
        }

        public Criteria andGroupMemberCountIsNotNull() {
            addCriterion("group_member_count is not null");
            return (Criteria) this;
        }

        public Criteria andGroupMemberCountEqualTo(Integer value) {
            addCriterion("group_member_count =", value, "groupMemberCount");
            return (Criteria) this;
        }

        public Criteria andGroupMemberCountNotEqualTo(Integer value) {
            addCriterion("group_member_count <>", value, "groupMemberCount");
            return (Criteria) this;
        }

        public Criteria andGroupMemberCountGreaterThan(Integer value) {
            addCriterion("group_member_count >", value, "groupMemberCount");
            return (Criteria) this;
        }

        public Criteria andGroupMemberCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("group_member_count >=", value, "groupMemberCount");
            return (Criteria) this;
        }

        public Criteria andGroupMemberCountLessThan(Integer value) {
            addCriterion("group_member_count <", value, "groupMemberCount");
            return (Criteria) this;
        }

        public Criteria andGroupMemberCountLessThanOrEqualTo(Integer value) {
            addCriterion("group_member_count <=", value, "groupMemberCount");
            return (Criteria) this;
        }

        public Criteria andGroupMemberCountIn(List<Integer> values) {
            addCriterion("group_member_count in", values, "groupMemberCount");
            return (Criteria) this;
        }

        public Criteria andGroupMemberCountNotIn(List<Integer> values) {
            addCriterion("group_member_count not in", values, "groupMemberCount");
            return (Criteria) this;
        }

        public Criteria andGroupMemberCountBetween(Integer value1, Integer value2) {
            addCriterion("group_member_count between", value1, value2, "groupMemberCount");
            return (Criteria) this;
        }

        public Criteria andGroupMemberCountNotBetween(Integer value1, Integer value2) {
            addCriterion("group_member_count not between", value1, value2, "groupMemberCount");
            return (Criteria) this;
        }

        public Criteria andGroupNameIsNull() {
            addCriterion("group_name is null");
            return (Criteria) this;
        }

        public Criteria andGroupNameIsNotNull() {
            addCriterion("group_name is not null");
            return (Criteria) this;
        }

        public Criteria andGroupNameEqualTo(String value) {
            addCriterion("group_name =", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameNotEqualTo(String value) {
            addCriterion("group_name <>", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameGreaterThan(String value) {
            addCriterion("group_name >", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameGreaterThanOrEqualTo(String value) {
            addCriterion("group_name >=", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameLessThan(String value) {
            addCriterion("group_name <", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameLessThanOrEqualTo(String value) {
            addCriterion("group_name <=", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameLike(String value) {
            addCriterion("group_name like", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameNotLike(String value) {
            addCriterion("group_name not like", value, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameIn(List<String> values) {
            addCriterion("group_name in", values, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameNotIn(List<String> values) {
            addCriterion("group_name not in", values, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameBetween(String value1, String value2) {
            addCriterion("group_name between", value1, value2, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupNameNotBetween(String value1, String value2) {
            addCriterion("group_name not between", value1, value2, "groupName");
            return (Criteria) this;
        }

        public Criteria andGroupMasterIdIsNull() {
            addCriterion("group_master_id is null");
            return (Criteria) this;
        }

        public Criteria andGroupMasterIdIsNotNull() {
            addCriterion("group_master_id is not null");
            return (Criteria) this;
        }

        public Criteria andGroupMasterIdEqualTo(Integer value) {
            addCriterion("group_master_id =", value, "groupMasterId");
            return (Criteria) this;
        }

        public Criteria andGroupMasterIdNotEqualTo(Integer value) {
            addCriterion("group_master_id <>", value, "groupMasterId");
            return (Criteria) this;
        }

        public Criteria andGroupMasterIdGreaterThan(Integer value) {
            addCriterion("group_master_id >", value, "groupMasterId");
            return (Criteria) this;
        }

        public Criteria andGroupMasterIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("group_master_id >=", value, "groupMasterId");
            return (Criteria) this;
        }

        public Criteria andGroupMasterIdLessThan(Integer value) {
            addCriterion("group_master_id <", value, "groupMasterId");
            return (Criteria) this;
        }

        public Criteria andGroupMasterIdLessThanOrEqualTo(Integer value) {
            addCriterion("group_master_id <=", value, "groupMasterId");
            return (Criteria) this;
        }

        public Criteria andGroupMasterIdIn(List<Integer> values) {
            addCriterion("group_master_id in", values, "groupMasterId");
            return (Criteria) this;
        }

        public Criteria andGroupMasterIdNotIn(List<Integer> values) {
            addCriterion("group_master_id not in", values, "groupMasterId");
            return (Criteria) this;
        }

        public Criteria andGroupMasterIdBetween(Integer value1, Integer value2) {
            addCriterion("group_master_id between", value1, value2, "groupMasterId");
            return (Criteria) this;
        }

        public Criteria andGroupMasterIdNotBetween(Integer value1, Integer value2) {
            addCriterion("group_master_id not between", value1, value2, "groupMasterId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andGroupIconIsNull() {
            addCriterion("group_icon is null");
            return (Criteria) this;
        }

        public Criteria andGroupIconIsNotNull() {
            addCriterion("group_icon is not null");
            return (Criteria) this;
        }

        public Criteria andGroupIconEqualTo(String value) {
            addCriterion("group_icon =", value, "groupIcon");
            return (Criteria) this;
        }

        public Criteria andGroupIconNotEqualTo(String value) {
            addCriterion("group_icon <>", value, "groupIcon");
            return (Criteria) this;
        }

        public Criteria andGroupIconGreaterThan(String value) {
            addCriterion("group_icon >", value, "groupIcon");
            return (Criteria) this;
        }

        public Criteria andGroupIconGreaterThanOrEqualTo(String value) {
            addCriterion("group_icon >=", value, "groupIcon");
            return (Criteria) this;
        }

        public Criteria andGroupIconLessThan(String value) {
            addCriterion("group_icon <", value, "groupIcon");
            return (Criteria) this;
        }

        public Criteria andGroupIconLessThanOrEqualTo(String value) {
            addCriterion("group_icon <=", value, "groupIcon");
            return (Criteria) this;
        }

        public Criteria andGroupIconLike(String value) {
            addCriterion("group_icon like", value, "groupIcon");
            return (Criteria) this;
        }

        public Criteria andGroupIconNotLike(String value) {
            addCriterion("group_icon not like", value, "groupIcon");
            return (Criteria) this;
        }

        public Criteria andGroupIconIn(List<String> values) {
            addCriterion("group_icon in", values, "groupIcon");
            return (Criteria) this;
        }

        public Criteria andGroupIconNotIn(List<String> values) {
            addCriterion("group_icon not in", values, "groupIcon");
            return (Criteria) this;
        }

        public Criteria andGroupIconBetween(String value1, String value2) {
            addCriterion("group_icon between", value1, value2, "groupIcon");
            return (Criteria) this;
        }

        public Criteria andGroupIconNotBetween(String value1, String value2) {
            addCriterion("group_icon not between", value1, value2, "groupIcon");
            return (Criteria) this;
        }

        public Criteria andBriefInfoIsNull() {
            addCriterion("brief_info is null");
            return (Criteria) this;
        }

        public Criteria andBriefInfoIsNotNull() {
            addCriterion("brief_info is not null");
            return (Criteria) this;
        }

        public Criteria andBriefInfoEqualTo(String value) {
            addCriterion("brief_info =", value, "briefInfo");
            return (Criteria) this;
        }

        public Criteria andBriefInfoNotEqualTo(String value) {
            addCriterion("brief_info <>", value, "briefInfo");
            return (Criteria) this;
        }

        public Criteria andBriefInfoGreaterThan(String value) {
            addCriterion("brief_info >", value, "briefInfo");
            return (Criteria) this;
        }

        public Criteria andBriefInfoGreaterThanOrEqualTo(String value) {
            addCriterion("brief_info >=", value, "briefInfo");
            return (Criteria) this;
        }

        public Criteria andBriefInfoLessThan(String value) {
            addCriterion("brief_info <", value, "briefInfo");
            return (Criteria) this;
        }

        public Criteria andBriefInfoLessThanOrEqualTo(String value) {
            addCriterion("brief_info <=", value, "briefInfo");
            return (Criteria) this;
        }

        public Criteria andBriefInfoLike(String value) {
            addCriterion("brief_info like", value, "briefInfo");
            return (Criteria) this;
        }

        public Criteria andBriefInfoNotLike(String value) {
            addCriterion("brief_info not like", value, "briefInfo");
            return (Criteria) this;
        }

        public Criteria andBriefInfoIn(List<String> values) {
            addCriterion("brief_info in", values, "briefInfo");
            return (Criteria) this;
        }

        public Criteria andBriefInfoNotIn(List<String> values) {
            addCriterion("brief_info not in", values, "briefInfo");
            return (Criteria) this;
        }

        public Criteria andBriefInfoBetween(String value1, String value2) {
            addCriterion("brief_info between", value1, value2, "briefInfo");
            return (Criteria) this;
        }

        public Criteria andBriefInfoNotBetween(String value1, String value2) {
            addCriterion("brief_info not between", value1, value2, "briefInfo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_group
     *
     * @mbg.generated do_not_delete_during_merge Sat Aug 21 23:34:51 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_group
     *
     * @mbg.generated Sat Aug 21 23:34:51 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}