package com.ctgu.j604.springbootchat.model;

import java.util.Date;

public class MessageOneToOne {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_single.id
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_single.from_user_id
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    private Integer fromUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_single.to_user_id
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    private Integer toUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_single.message
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_single.send_time
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    private Date sendTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_single.id
     *
     * @return the value of msg_single.id
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_single.id
     *
     * @param id the value for msg_single.id
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_single.from_user_id
     *
     * @return the value of msg_single.from_user_id
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    public Integer getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_single.from_user_id
     *
     * @param fromUserId the value for msg_single.from_user_id
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    public void setFromUserId(Integer fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_single.to_user_id
     *
     * @return the value of msg_single.to_user_id
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    public Integer getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_single.to_user_id
     *
     * @param toUserId the value for msg_single.to_user_id
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    public void setToUserId(Integer toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_single.message
     *
     * @return the value of msg_single.message
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_single.message
     *
     * @param message the value for msg_single.message
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_single.send_time
     *
     * @return the value of msg_single.send_time
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_single.send_time
     *
     * @param sendTime the value for msg_single.send_time
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }
}