package com.ctgu.j604.springbootchat.model;

import java.util.Date;

public class UnreadMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unread_message.id
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unread_message.to_user_num
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    private String toUserNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unread_message.to_user_id
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    private Integer toUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unread_message.from_user_num
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    private String fromUserNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unread_message.from_user_id
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    private Integer fromUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unread_message.content
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unread_message.send_time
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unread_message.msg_type_code
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    private Integer msgTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unread_message.from_member_num
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    private String fromMemberNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unread_message.id
     *
     * @return the value of unread_message.id
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unread_message.id
     *
     * @param id the value for unread_message.id
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unread_message.to_user_num
     *
     * @return the value of unread_message.to_user_num
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    public String getToUserNum() {
        return toUserNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unread_message.to_user_num
     *
     * @param toUserNum the value for unread_message.to_user_num
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    public void setToUserNum(String toUserNum) {
        this.toUserNum = toUserNum == null ? null : toUserNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unread_message.to_user_id
     *
     * @return the value of unread_message.to_user_id
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    public Integer getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unread_message.to_user_id
     *
     * @param toUserId the value for unread_message.to_user_id
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    public void setToUserId(Integer toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unread_message.from_user_num
     *
     * @return the value of unread_message.from_user_num
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    public String getFromUserNum() {
        return fromUserNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unread_message.from_user_num
     *
     * @param fromUserNum the value for unread_message.from_user_num
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    public void setFromUserNum(String fromUserNum) {
        this.fromUserNum = fromUserNum == null ? null : fromUserNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unread_message.from_user_id
     *
     * @return the value of unread_message.from_user_id
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    public Integer getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unread_message.from_user_id
     *
     * @param fromUserId the value for unread_message.from_user_id
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    public void setFromUserId(Integer fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unread_message.content
     *
     * @return the value of unread_message.content
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unread_message.content
     *
     * @param content the value for unread_message.content
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unread_message.send_time
     *
     * @return the value of unread_message.send_time
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unread_message.send_time
     *
     * @param sendTime the value for unread_message.send_time
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unread_message.msg_type_code
     *
     * @return the value of unread_message.msg_type_code
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    public Integer getMsgTypeCode() {
        return msgTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unread_message.msg_type_code
     *
     * @param msgTypeCode the value for unread_message.msg_type_code
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    public void setMsgTypeCode(Integer msgTypeCode) {
        this.msgTypeCode = msgTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unread_message.from_member_num
     *
     * @return the value of unread_message.from_member_num
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    public String getFromMemberNum() {
        return fromMemberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unread_message.from_member_num
     *
     * @param fromMemberNum the value for unread_message.from_member_num
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    public void setFromMemberNum(String fromMemberNum) {
        this.fromMemberNum = fromMemberNum == null ? null : fromMemberNum.trim();
    }
}