package com.ctgu.j604.springbootchat.mapper;

import com.ctgu.j604.springbootchat.model.AutoSafetyMember;
import com.ctgu.j604.springbootchat.model.AutoSafetyMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AutoSafetyMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_report_safety
     *
     * @mbg.generated Fri Aug 27 23:12:51 CST 2021
     */
    long countByExample(AutoSafetyMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_report_safety
     *
     * @mbg.generated Fri Aug 27 23:12:51 CST 2021
     */
    int deleteByExample(AutoSafetyMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_report_safety
     *
     * @mbg.generated Fri Aug 27 23:12:51 CST 2021
     */
    int deleteByPrimaryKey(String stuNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_report_safety
     *
     * @mbg.generated Fri Aug 27 23:12:51 CST 2021
     */
    int insert(AutoSafetyMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_report_safety
     *
     * @mbg.generated Fri Aug 27 23:12:51 CST 2021
     */
    int insertSelective(AutoSafetyMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_report_safety
     *
     * @mbg.generated Fri Aug 27 23:12:51 CST 2021
     */
    List<AutoSafetyMember> selectByExample(AutoSafetyMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_report_safety
     *
     * @mbg.generated Fri Aug 27 23:12:51 CST 2021
     */
    AutoSafetyMember selectByPrimaryKey(String stuNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_report_safety
     *
     * @mbg.generated Fri Aug 27 23:12:51 CST 2021
     */
    int updateByExampleSelective(@Param("record") AutoSafetyMember record, @Param("example") AutoSafetyMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_report_safety
     *
     * @mbg.generated Fri Aug 27 23:12:51 CST 2021
     */
    int updateByExample(@Param("record") AutoSafetyMember record, @Param("example") AutoSafetyMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_report_safety
     *
     * @mbg.generated Fri Aug 27 23:12:51 CST 2021
     */
    int updateByPrimaryKeySelective(AutoSafetyMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_report_safety
     *
     * @mbg.generated Fri Aug 27 23:12:51 CST 2021
     */
    int updateByPrimaryKey(AutoSafetyMember record);
}