package com.ctgu.j604.springbootchat.mapper;

import com.ctgu.j604.springbootchat.model.FriendListInfo;
import com.ctgu.j604.springbootchat.model.FriendListInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FriendListInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_list_info
     *
     * @mbg.generated Tue Aug 17 11:14:25 CST 2021
     */
    long countByExample(FriendListInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_list_info
     *
     * @mbg.generated Tue Aug 17 11:14:25 CST 2021
     */
    int deleteByExample(FriendListInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_list_info
     *
     * @mbg.generated Tue Aug 17 11:14:25 CST 2021
     */
    int insert(FriendListInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_list_info
     *
     * @mbg.generated Tue Aug 17 11:14:25 CST 2021
     */
    int insertSelective(FriendListInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_list_info
     *
     * @mbg.generated Tue Aug 17 11:14:25 CST 2021
     */
    List<FriendListInfo> selectByExample(FriendListInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_list_info
     *
     * @mbg.generated Tue Aug 17 11:14:25 CST 2021
     */
    int updateByExampleSelective(@Param("record") FriendListInfo record, @Param("example") FriendListInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_list_info
     *
     * @mbg.generated Tue Aug 17 11:14:25 CST 2021
     */
    int updateByExample(@Param("record") FriendListInfo record, @Param("example") FriendListInfoExample example);
}