package com.ctgu.j604.springbootchat.mapper;

import com.ctgu.j604.springbootchat.model.LinkmanList;
import com.ctgu.j604.springbootchat.model.LinkmanListExample;
import com.ctgu.j604.springbootchat.model.LinkmanListKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LinkmanListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman_list
     *
     * @mbg.generated Sun Aug 22 16:06:14 CST 2021
     */
    long countByExample(LinkmanListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman_list
     *
     * @mbg.generated Sun Aug 22 16:06:14 CST 2021
     */
    int deleteByExample(LinkmanListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman_list
     *
     * @mbg.generated Sun Aug 22 16:06:14 CST 2021
     */
    int deleteByPrimaryKey(LinkmanListKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman_list
     *
     * @mbg.generated Sun Aug 22 16:06:14 CST 2021
     */
    int insert(LinkmanList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman_list
     *
     * @mbg.generated Sun Aug 22 16:06:14 CST 2021
     */
    int insertSelective(LinkmanList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman_list
     *
     * @mbg.generated Sun Aug 22 16:06:14 CST 2021
     */
    List<LinkmanList> selectByExample(LinkmanListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman_list
     *
     * @mbg.generated Sun Aug 22 16:06:14 CST 2021
     */
    LinkmanList selectByPrimaryKey(LinkmanListKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman_list
     *
     * @mbg.generated Sun Aug 22 16:06:14 CST 2021
     */
    int updateByExampleSelective(@Param("record") LinkmanList record, @Param("example") LinkmanListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman_list
     *
     * @mbg.generated Sun Aug 22 16:06:14 CST 2021
     */
    int updateByExample(@Param("record") LinkmanList record, @Param("example") LinkmanListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman_list
     *
     * @mbg.generated Sun Aug 22 16:06:14 CST 2021
     */
    int updateByPrimaryKeySelective(LinkmanList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table linkman_list
     *
     * @mbg.generated Sun Aug 22 16:06:14 CST 2021
     */
    int updateByPrimaryKey(LinkmanList record);
}