package com.ctgu.j604.springbootchat.mapper;

import com.ctgu.j604.springbootchat.model.MessageHistory;
import com.ctgu.j604.springbootchat.model.MessageHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_history
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    long countByExample(MessageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_history
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    int deleteByExample(MessageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_history
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_history
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    int insert(MessageHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_history
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    int insertSelective(MessageHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_history
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    List<MessageHistory> selectByExample(MessageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_history
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    MessageHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_history
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    int updateByExampleSelective(@Param("record") MessageHistory record, @Param("example") MessageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_history
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    int updateByExample(@Param("record") MessageHistory record, @Param("example") MessageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_history
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    int updateByPrimaryKeySelective(MessageHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_history
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    int updateByPrimaryKey(MessageHistory record);
}