package com.ctgu.j604.springbootchat.mapper;

import com.ctgu.j604.springbootchat.model.MessageOneToOne;
import com.ctgu.j604.springbootchat.model.MessageOneToOneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageOneToOneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_single
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    long countByExample(MessageOneToOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_single
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    int deleteByExample(MessageOneToOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_single
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_single
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    int insert(MessageOneToOne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_single
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    int insertSelective(MessageOneToOne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_single
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    List<MessageOneToOne> selectByExample(MessageOneToOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_single
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    MessageOneToOne selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_single
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    int updateByExampleSelective(@Param("record") MessageOneToOne record, @Param("example") MessageOneToOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_single
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    int updateByExample(@Param("record") MessageOneToOne record, @Param("example") MessageOneToOneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_single
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    int updateByPrimaryKeySelective(MessageOneToOne record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_single
     *
     * @mbg.generated Wed Aug 18 01:19:39 CST 2021
     */
    int updateByPrimaryKey(MessageOneToOne record);
}