package com.ctgu.j604.springbootchat.mapper;

import com.ctgu.j604.springbootchat.model.UnreadMessage;
import com.ctgu.j604.springbootchat.model.UnreadMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UnreadMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unread_message
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    long countByExample(UnreadMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unread_message
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    int deleteByExample(UnreadMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unread_message
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unread_message
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    int insert(UnreadMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unread_message
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    int insertSelective(UnreadMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unread_message
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    List<UnreadMessage> selectByExample(UnreadMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unread_message
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    UnreadMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unread_message
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    int updateByExampleSelective(@Param("record") UnreadMessage record, @Param("example") UnreadMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unread_message
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    int updateByExample(@Param("record") UnreadMessage record, @Param("example") UnreadMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unread_message
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    int updateByPrimaryKeySelective(UnreadMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unread_message
     *
     * @mbg.generated Thu Aug 19 19:01:48 CST 2021
     */
    int updateByPrimaryKey(UnreadMessage record);
}